services:
  mysql:
    image: mysql:8
    container_name: mysql-hospital
    restart: always
    ports:
      - "3307:3306"   # different host port
    volumes:
      - hospital-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Aps@19951986
      MYSQL_DATABASE: hospital_db
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pAps@19951986"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: spring-login:0.0.1
    container_name: hospital-app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8081:8080"   # different host port
    environment:
      SERVER_PORT: 8080
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hospital_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Aps@19951986

volumes:
  hospital-mysql-data: