apiVersion: v1
kind: Service
metadata:
  name: springlogin
  namespace: default
  labels:
    app: springlogin
spec:
  type: LoadBalancer
  selector:
    app: springlogin
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30536
      protocol: TCP
